export default {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  HOME_NAVIGATOR: 'HOME_NAVIGATOR',
  LOG_NAVIGATOR: 'LOG_NAVIGATOR',
  CALENDAR_NAVIGATOR: 'CALENDAR_NAVIGATOR',
  MAINTAB: 'MAINTAB',
  HOME: 'HOME',
  LOG: 'LOG',
  YOUR_EXERCISE: 'YOUR_EXERCISE',
  EX_DETAIL: 'EX_DETAIL',
  EX_INFO: 'EX_INFO',
  DETAIL_LOG: 'DETAIL_LOG',
};
